%%
% ColonyCounter.
% Copyright (C) 2022 A. Bachmann, A. Dupont, J. Stegmaier
%
% Licensed under the Apache License, Version 2.0 (the "License");
% you may not use this file except in compliance with the License.
% You may obtain a copy of the Liceense at
% 
%     http://www.apache.org/licenses/LICENSE-2.0
% 
% Unless required by applicable law or agreed to in writing, software
% distributed under the License is distributed on an "AS IS" BASIS,
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
% See the License for the specific language governing permissions and
% limitations under the License.
%
% Please refer to the documentation for more information about the software
% as well as for installation instructions.
%
% If you use this application for your work, please cite the repository and one
% of the following publications:
%
% TBA
%
%%

helpText = {'1,2,3,4,5,6,7: Toggles the visualization of different channels and detections', ...
            'Up Arrow: Increase selected threshold (highlighted in red)', ...
            'Down Arrow: Decrease selected threshold (highlighted in red)', ...
            'Left Arrow: Go to previous slice (only works in slice mode)', ...
            'Right Arrow: Go to next slice (only works in slice mode)', ...
            '+/-: Increase or decrease gamma exponent for contrast adjustment', ...
            'A: Add/remove bacteria or colonies (left-click to add, right-click to delete)', ...
            'B: Boundary visualization on/off', ...
            'C: Toggle color map', ...
            'D: Detections visualization on/off', ...
            'E: Export results (two csv files *_grouped.csv and *_counts.csv)', ...
            'H: Show this help dialog so you probably already know about this button :-)', ...
            'I: Show information about colony ids and their size', ... 
            'S: Show/hide the parameter information on the top left', ...
            'M: Show measurements for current parameter selection', ...
            'O: Zoom out to the original view', ...
            'P: Change to the next parameter', ...
            'R: Reset parameters to the default values', ...
            'V: Toggle aspect ratio (stretch or equal)', ...
            'Mouse Wheel: Scroll through slices (only works in slice-mode)', ...
            'CTRL + Mouse Wheel: Zoom in/out in a Google-Maps like behavior', ...
            '', ...
            'Hint: In case key presses show no effect, left click once on the image and try hitting the button again. This only happens if the window looses the focus.'};

helpdlg(helpText);